Repository SergiAlbalat/ChemSecure, pull requests merged in 2025-05, with the labels that each got.

#6 Feature/api create models
  ChemSecureApi/ChemSecureApi.csproj
  ChemSecureApi/Controllers/WeatherForecastController.cs
  ChemSecureApi/Model/Tank.cs
  ChemSecureApi/Model/Trip.cs
  ChemSecureApi/Model/Truck.cs
  ChemSecureApi/Model/User.cs
  ChemSecureApi/WeatherForecast.cs
Labels: enhancement

#7 #4.feature(api): carpeta data feta
  ChemSecureApi/Data/AppDbContext.cs
  ChemSecureApi/Program.cs
  ChemSecureApi/appsettings.json
Labels: enhancement

#10 #8.Feature(api): Rols afegits
  ChemSecureApi/Program.cs
  ChemSecureApi/Tools/RoleTools.cs
Labels: enhancement

#11 #2 Tank page created
  ChemSecureWeb/ChemSecureWeb.csproj
  ChemSecureWeb/Pages/Shared/_Layout.cshtml
  ChemSecureWeb/Pages/Tank.cshtml
  ChemSecureWeb/Pages/Tank.cshtml.cs
Labels: enhancement

#16 #9.Feature(api): Controlador per autentificacio implementat
  ChemSecureApi/ChemSecureApi.csproj
  ChemSecureApi/Controllers/AuthController.cs
  ChemSecureApi/DTOs/LoginDTO.cs
  ChemSecureApi/DTOs/RegisterDTO.cs
  ChemSecureApi/Program.cs
  ChemSecureApi/Properties/launchSettings.json
Labels: enhancement

#19 Pass login register to dev/client
  ChemSecureWeb/Model/LoginDTO.cs
  ChemSecureWeb/Model/RegisterDTO.cs
  ChemSecureWeb/Pages/Index.cshtml
Labels: documentation

#20 Dev/api to dev merge day 1
  ChemSecureApi/ChemSecureApi.csproj
  ChemSecureApi/Controllers/AuthController.cs
  ChemSecureApi/Controllers/TankController.cs
  ChemSecureApi/Controllers/WeatherForecastController.cs
  ChemSecureApi/DTOs/LoginDTO.cs
  ChemSecureApi/DTOs/RegisterDTO.cs
  ChemSecureApi/DTOs/TankGetDTO.cs
  ChemSecureApi/DTOs/TankInsertDTO.cs
  ChemSecureApi/Data/AppDbContext.cs
  ChemSecureApi/Model/Tank.cs
  ChemSecureApi/Model/Trip.cs
  ChemSecureApi/Model/Truck.cs
  ChemSecureApi/Model/User.cs
  ChemSecureApi/Program.cs
  ChemSecureApi/Properties/launchSettings.json
  ChemSecureApi/Tools/RoleTools.cs
  ChemSecureApi/WeatherForecast.cs
  ChemSecureApi/appsettings.json
Labels: documentation

#22 Bugfix/api fix tankcontroller method names
  ChemSecureApi/Controllers/AuthController.cs
  ChemSecureApi/Controllers/TankController.cs
Labels: enhancement

#24 #23.feature(api): GetUserTanks created succesfully
  ChemSecureApi/Controllers/TankController.cs
Labels: enhancement

#29 #27.Feature(api): Migrations to the database applied
  ChemSecureApi/Data/AppDbContext.cs
  ChemSecureApi/Migrations/20250520075122_InitialMigratrion.Designer.cs
  ChemSecureApi/Migrations/20250520075122_InitialMigratrion.cs
  ChemSecureApi/Migrations/AppDbContextModelSnapshot.cs
Labels: enhancement

#31 #30.Bugfix(api): tankcontroller methods now have a good access contro…
  ChemSecureApi/Controllers/TankController.cs
Labels: enhancement

#36 #34.Bugfix(API): User controller done
  ChemSecureApi/Controllers/AuthController.cs
  ChemSecureApi/Controllers/UserController.cs
  ChemSecureApi/DTOs/UserDTO.cs
Labels: enhancement

#38 Dev/api to Dev day 2
  ChemSecureApi/Controllers/AuthController.cs
  ChemSecureApi/Controllers/TankController.cs
  ChemSecureApi/Controllers/UserController.cs
  ChemSecureApi/DTOs/UserDTO.cs
  ChemSecureApi/Data/AppDbContext.cs
  ChemSecureApi/Migrations/20250520075122_InitialMigratrion.Designer.cs
  ChemSecureApi/Migrations/20250520075122_InitialMigratrion.cs
  ChemSecureApi/Migrations/AppDbContextModelSnapshot.cs
  ChemSecureApi/appsettings.json
Labels: documentation

#43 #41.Feature(api): GetUsers method added correctly
  ChemSecureApi/Controllers/UserController.cs
Labels: enhancement

#44 #42. Bugfix(API): Comments changed to english.
  ChemSecureApi/Controllers/TankController.cs
Labels: documentation

#58 #45 . Fix(API): DTO from Tanks changed, method changed to work with C…
  ChemSecureApi/Controllers/TankController.cs
  ChemSecureApi/DTOs/TankGetDTO.cs
  ChemSecureApi/DTOs/TankInsertDTO.cs
  ChemSecureApi/DTOs/UserDTO.cs
  ChemSecureApi/DTOs/UserTankDTO.cs
Labels: bug

#75 #64 Login logic finished
  ChemSecureWeb/Pages/Login.cshtml
  ChemSecureWeb/Program.cs
  ChemSecureWeb/Tools/TokenHelper.cs
  ChemSecureWeb/appsettings.json
Labels: enhancement

#87 #78.Bugfix(api): authorizes fixeds
  ChemSecureApi/Controllers/TankController.cs
Labels: bug

#90 #79.Feature(Web): tank details connection done
  ChemSecureWeb/Pages/Tank.cshtml.cs
  ChemSecureWeb/Pages/TankDetails.cshtml.cs
Labels: enhancement

#95 #94. LogOut fixed.
  ChemSecureWeb/Pages/Shared/_Layout.cshtml
  ChemSecureWeb/Pages/TankDetails.cshtml
Labels: enhancement

#96 #81.Feature(api): Warnings added
  ChemSecureApi/Controllers/TankController.cs
  ChemSecureApi/Controllers/WarningController.cs
  ChemSecureApi/DTOs/WarningDTO.cs
  ChemSecureApi/Data/AppDbContext.cs
  ChemSecureApi/Model/Warning.cs
Labels: enhancement

#108 #77.Documentation(api): methods documentation completed
  ChemSecureApi/Controllers/AuthController.cs
  ChemSecureApi/Controllers/TankController.cs
  ChemSecureApi/Controllers/UserController.cs
  ChemSecureApi/Controllers/WarningController.cs
Labels: documentation

#112 #111.Feature(web): api url updated
  ChemSecureWeb/appsettings.json
Labels: enhancement

#113 Dev to main api url changed
  ChemSecureWeb/appsettings.json
Labels: enhancement
